/* Erzeugt von tools/jedipedia_titel.py – nicht von Hand ändern.

   Der Katalog ist englisch, die Jedipedia deutsch: »Bespin Guard«
   heißt dort »Bespin-Sicherheitskräfte«. Wo der Begriff nicht schon
   selbst ein Artikeltitel ist, steht hier, wie der Artikel wirklich
   heißt. Nachgeschlagen, nicht geraten: Jeder Eintrag kam aus der
   MediaWiki-Schnittstelle des Wikis, und Begriffsklärungsseiten
   sind aussortiert.

   Schlüssel sind **Namen**, nie BrickLinks Beschreibungen – die
   löst die Begriffsbildung vorher heraus.

   190 Einträge. */
const JEDIPEDIA_TITEL = {
  "2-1B Medical Droid": "2-1B",
  "AT-AT Driver": "AT-AT-Piloten",
  "AT-DP Pilot": "AT-DP-Piloten",
  "Assassin Droid": "Attentäterdroide",
  "B2EMO Droid": "B2EMO",
  "Battle Droid": "B1-Kampfdroide",
  "Battle Droid Commander": "OOM-Kommandodroide",
  "Battle Droid Pilot": "B1-Kampfdroide",
  "Beach Luke": "Luke Skywalker",
  "Bespin Guard": "Bespin-Sicherheitskräfte",
  "Bith Musician": "Bith",
  "Bounty Hunter C-3PO": "C-3PO",
  "Buzz Droid": "Pistoeka-Sabotagedroide",
  "Captain Antilles": "Raymus Antilles",
  "Captain Tarpals": "Roos Tarpals",
  "Carasynthia 'Cara' Dune": "Carasynthia Dune",
  "Cassian Andor": "Cassian Jeron Andor",
  "Chancellor Palpatine": "Sheev Palpatine",
  "Clone ARC Trooper Corporal Echo, Experimental Unit Clone Force 99": "CT-1409",
  "Clone ARC Trooper Fives, 501st Legion": "CT-5555",
  "Clone ARC Trooper Hammer, Rancor Battalion": "Rancor-Bataillon",
  "Clone ARF Trooper Razor / Stak, 91st Mobile Reconnaissance Corps Lightning Squadron": "91. Mobiles Aufklärungskorps",
  "Clone ARF Trooper, Rancor Battalion": "Rancor-Bataillon",
  "Clone Airborne Trooper": "Klonkrieger",
  "Clone Airborne Trooper, 212th Attack Battalion": "212. Angriffsbataillon",
  "Clone BARC Trooper, 91st Mobile Reconnaissance Corps": "91. Mobiles Aufklärungskorps",
  "Clone Bomb Squad Trooper": "Klonkrieger",
  "Clone Cadet": "Klon-Kadetten",
  "Clone Captain Vaughn, 501st Legion, 332nd Company": "CT-0292",
  "Clone Commander Bacara": "Commander Bacara",
  "Clone Commando Commander Crosshair, Imperial Elite Squad": "Crosshair",
  "Clone Commando Sergeant Hunter, Experimental Unit Clone Force 99": "CT-9901",
  "Clone Commando Wrecker, Experimental Unit Clone Force 99": "Wrecker",
  "Clone Heavy Trooper, 501st Legion": "501. Sturmtruppenlegion",
  "Clone Jet Trooper, 501st Legion": "501. Sturmtruppenlegion",
  "Clone Scout Trooper Episode 3": "Klonkrieger",
  "Clone Scout Trooper, 41st Elite Corps": "41. Elitekorps",
  "Clone Shock Trooper, Coruscant Guard": "Coruscant-Sicherheitskräfte",
  "Clone Trooper": "Klonkrieger",
  "Clone Trooper Captain": "Klonkrieger",
  "Clone Trooper Captain Rex, 501st Legion": "CT-7567",
  "Clone Trooper Commander": "Klon-Kommandant",
  "Clone Trooper Commander Bly": "Commander Bly",
  "Clone Trooper Commander Cody, 212th Attack Battalion": "Commander Cody",
  "Clone Trooper Commander Fox, Coruscant Guard": "Commander Fox",
  "Clone Trooper Commander Gree, 41st Elite Corps": "Commander Gree",
  "Clone Trooper Commander Wolffe, 104th Battalion 'Wolfpack'": "CC-3636",
  "Clone Trooper Commander, 187th Legion": "187. Legion",
  "Clone Trooper Gunner": "Klonkrieger",
  "Clone Trooper Lieutenant": "Klonkrieger",
  "Clone Trooper Officer, 501st Legion": "501. Sturmtruppenlegion",
  "Clone Trooper Pilot": "Klon-Piloten",
  "Clone Trooper Pilot Odd Ball": "Odd Ball",
  "Clone Trooper Pilot, 501st Legion": "501. Sturmtruppenlegion",
  "Clone Trooper Sergeant": "Klonkrieger",
  "Clone Trooper Specialist, 501st Legion": "501. Sturmtruppenlegion",
  "Clone Trooper V-wing Pilot": "Klon-Piloten",
  "Clone Trooper, 104th Battalion 'Wolfpack'": "104. Bataillon",
  "Clone Trooper, 187th Legion": "187. Legion",
  "Clone Trooper, 212th Attack Battalion": "212. Angriffsbataillon",
  "Clone Trooper, 327th Star Corps": "327. Sternenkorps",
  "Clone Trooper, 41st Elite Corps": "41. Elitekorps",
  "Clone Trooper, 442nd Siege Battalion": "442. Belagerungsbataillon",
  "Clone Trooper, 501st Legion": "501. Sturmtruppenlegion",
  "Clone Trooper, 501st Legion, 332nd Company": "501. Sturmtruppenlegion",
  "Clone Trooper, 91st Mobile Reconnaissance Corps": "91. Mobiles Aufklärungskorps",
  "Commander Wolffe": "CC-3636",
  "Commando Droid": "BX-Kommandodroide",
  "Commando Droid Captain": "BX-Kommandodroide",
  "Count Dooku": "Dooku",
  "DJ Code Breaker": "DJ",
  "DRK-1 Dark Eye Probe Droid": "DRK-1-Sonde",
  "Dark Trooper": "Dunkle Truppen",
  "Darth Maul": "Maul",
  "Darth Vader": "Anakin Skywalker",
  "Din Grogu / The Child / 'Baby Yoda'": "Din Grogu",
  "Dr. Cornelius Evazan": "Cornelius Evazan",
  "Dwarf Spider Droid": "ZSD1-Zwergspinnendroide",
  "Elite Praetorian Guard": "Prätorianergarde",
  "Emperor Palpatine": "Sheev Palpatine",
  "Endor Rebel Commando": "Infanterie (Rebellen-Allianz)",
  "FA-4 Pilot Droid": "FA-4 Pilotendroide",
  "First Order Crew Member": "Erste Ordnung",
  "First Order Flametrooper": "Sturmtruppen der Ersten Ordnung",
  "First Order Heavy Assault Stormtrooper": "Sturmtruppen der Ersten Ordnung",
  "First Order Officer": "Erste Ordnung",
  "First Order Snowtrooper": "Schneetruppen der Ersten Ordnung",
  "First Order Stormtrooper": "Sturmtruppen der Ersten Ordnung",
  "First Order Stormtrooper Executioner": "Exekutionstruppen",
  "First Order Stormtrooper Officer": "Sturmtruppen der Ersten Ordnung",
  "First Order TIE Fighter Pilot": "TIE-Piloten",
  "First Order Walker Driver": "Erste Ordnung",
  "Galactic Marine Clone Trooper": "21. Nova-Korps",
  "Gamorrean Guard": "Gamorreaner",
  "General Hux": "Armitage Hux",
  "General Maximillian Veers": "Maximilian Veers",
  "Geonosian": "Geonosianer",
  "Geonosian Warrior": "Geonosianer",
  "Geonosian Zombie": "Geonosianer",
  "Gonk Droid": "GNK-Energiedroide",
  "Gonk Droid, Experimental Unit Clone Force 99": "Kloneinheit 99",
  "Grand Admiral Thrawn": "Mitth'raw'nuruodo",
  "Grand Moff Wilhuff Tarkin": "Wilhuff Tarkin",
  "Gungan Soldier": "Gungan",
  "Hot Tub Stormtrooper": "Sturmtruppen",
  "Hoth Rebel Trooper": "Infanterie (Rebellen-Allianz)",
  "IG-100 MagnaGuard / Magna Droid": "IG-100 MagnaWächter",
  "IG-88": "IG-88 Attentäterdroide",
  "Imperial Artillery Stormtrooper": "Sturmtruppen",
  "Imperial Death Trooper": "Todestruppen",
  "Imperial Gunner": "Imperiale Waffentechniker",
  "Imperial Hovertank Pilot": "Sturmtruppen",
  "Imperial Inquisitor Fifth Brother": "Fünfter Bruder",
  "Imperial Jet Pack Trooper": "Sturmtruppen",
  "Imperial Patrol Trooper": "Patrouillentruppen",
  "Imperial Praetorian Guard": "Prätorianergarde",
  "Imperial Probe Droid": "Aufklärungsdroide",
  "Imperial Royal Guard": "Imperiale Garde",
  "Imperial Scout Trooper": "Scouttruppen",
  "Imperial Shadow Stormtrooper": "Schattentruppen",
  "Imperial Shadow Trooper": "Schattentruppen",
  "Imperial Shock Trooper": "Imperiale Stoßtruppen",
  "Imperial Stormtrooper": "Sturmtruppen",
  "Imperial Stormtrooper Sergeant": "Sturmtruppen",
  "Imperial TIE Bomber Pilot": "TIE-Piloten",
  "Imperial TIE Fighter / Interceptor Pilot": "TIE-Piloten",
  "Imperial TIE Fighter / Striker Pilot": "TIE-Piloten",
  "Imperial TIE Fighter Pilot": "TIE-Piloten",
  "Imperial Trooper": "Sturmtruppen",
  "Inferno Squad Agent": "Inferno-Trupp",
  "Interrogation Droid": "IT-O Verhördroide",
  "Jabba the Hutt": "Jabba Desilijic Tiure",
  "K-2SO Droid": "K-2SO",
  "Klatooinian Raider": "Klatooinianer",
  "Knight of Ren": "Ritter von Ren",
  "Labria": "Kardue'sai'Malloc",
  "Lando Calrissian": "Landonis Balthazar Calrissian",
  "Lieutenant Connix": "Kaydel Ko Connix",
  "Mandalorian Death Watch Warrior": "Todeswache",
  "Mandalorian Fleet Commander": "Mandalorianer",
  "Mandalorian Loyalist": "Mandalorianer",
  "Mandalorian Nite Owl": "Nachteulen",
  "Mandalorian Super Commando": "Mando Ori'ramikade",
  "Mandalorian Tribe Warrior": "Mandalorianer",
  "Mandalorian Warrior": "Mandalorianer",
  "Mimban Stormtrooper": "Sturmtruppen",
  "Moff Gideon": "Gideon (Moff)",
  "Mouse Droid": "MSE-6-Mausdroide",
  "NI-L8 Protocol Droid": "Protokolldroide",
  "Pit Droid": "DUM-Serie Boxendroide",
  "Poggle the Lesser": "Poggle",
  "Pre-Mor Security Deputy Inspector Syril Karn": "Syril Karn",
  "Princess Leia": "Prinzessin Leia",
  "Professor Huyang": "Huyang",
  "Protocol Droid": "Protokolldroide",
  "Rebel Fleet Trooper": "Infanterie (Rebellen-Allianz)",
  "Rebel Fleet Trooper / Rebel Scout Trooper": "Infanterie (Rebellen-Allianz)",
  "Rebel Pilot": "Rebellenpiloten",
  "Rebel Pilot A-wing": "Rebellenpiloten",
  "Rebel Pilot B-wing": "Rebellenpiloten",
  "Rebel Pilot U-wing": "Rebellenpiloten",
  "Rebel Trooper": "Infanterie (Rebellen-Allianz)",
  "Reindeer Gonk Droid": "GNK-Energiedroide",
  "Republic Trooper": "Armee der Galaktischen Republik",
  "Resistance Officer": "Widerstand",
  "Resistance Pilot X-wing": "Widerstand",
  "Resistance Soldier": "Widerstand",
  "Resistance Trooper": "Widerstand",
  "Rocket Battle Droid": "B1-Kampfdroide",
  "Rocket Battle Droid Commander": "OOM-Kommandodroide",
  "Sandtrooper": "Sandtruppen",
  "Sandtrooper Squad Leader": "Sandtruppen",
  "Scarif Stormtrooper": "Sturmtruppen",
  "Security Battle Droid": "B1-Kampfdroide",
  "Senate Commando": "Senatswache",
  "Senate Commando Captain": "Senatswache",
  "Shadow Guard": "Schattenwachen",
  "Snowman BB-8": "BB-8",
  "Special Forces Clone Trooper": "Klonkrieger",
  "Special Forces Commander": "Klon-Kommandant",
  "Super Battle Droid": "B2-Superkampfdroide",
  "Supreme Leader Kylo Ren": "Ben Solo",
  "The Armorer": "Waffenschmiedin",
  "The Grand Inquisitor": "Großinquisitor",
  "The Mandalorian / Din Djarin / 'Mando'": "Din Djarin",
  "Treadwell Droid": "WED Treadwell",
  "Tusken Raider": "Tusken-Räuber",
  "Vice Admiral Sloane": "Rae Sloane",
  "Wicket": "Wicket W. Warrick",
  "Wooof": "Klaatu"
};
